### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by luzpaz** [janestreet/sexplib#35]
```
$ pip3 install --user  git+https://github.com/janestreet/sexplib
Collecting git+https://github.com/janestreet/sexplib
  Cloning https://github.com/janestreet/sexplib to /tmp/pip-req-build-a0kyx9jj
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-a0kyx9jj/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-a0kyx9jj/
```

Python 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531] on linux
pip 18.0 from /usr/lib/python3.7/site-packages/pip (python 3.7)

**Comment by diml** [comment]
sexplib is an OCaml package and should be installed via [opam](https://opam.ocaml.org/). Hope that helps
